[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [] 
[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY}", url = "${VERIFIER_URL}" }




